#define DMA_IRQ_USART2_TX DMA1_Stream6_IRQHandler
#ifdef DMAv2
#define TCIF_USART2_TX ((DMA1->HISR & DMA_HISR_TCIF6)!=0)
#define CTCIF_USART2_TX (DMA1->HIFCR |= DMA_HIFCR_CTCIF6)
#endif
#ifdef DMAv1
#define TCIF_USART2_TX ((DMA1->ISR & DMA_ISR_TCIF6)!=0)
#define CTCIF_USART2_TX (DMA1->IFCR |= DMA_IFCR_CTCIF6)
#endif

