[package]
name = "prot"
version = "0.1.0"
authors = ["Mohammed Alzakariya <lanhikarixx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
itertools = "0"
